### ISSUE TITLE
Putting tailwind classes on html elements in preact jsx doesn't render the class?

### ISSUE THREAD

**Issue by algoflows** [agneym/preact-cli-tailwind#13]
Hi guys,

Quick question. 

Placing styles in the style.css file seems to work as shown below... however if I place tailwind classes in the jsx on an element the classes don't get applied?

![image](https://user-images.githubusercontent.com/65465380/124457817-26203a80-dd84-11eb-8470-1869161be40b.png)

you see below green doesn't get applied while placing the class directly in the jsx... Is this a bug, or was this by design?

![image](https://user-images.githubusercontent.com/65465380/124458728-3c7ac600-dd85-11eb-8f49-b4da81753d69.png)

**Comment by agneym** [comment]
I'm not sure what the issue is, can you make me a reproducible example?

**Comment by algoflows** [comment]
Hey buddy need to check if I still have the repo, but basically I could add tailwind classes within the jsx, it wouldn't work. I try again with a fresh clone and see if the issue persists :).

**Comment by agneym** [comment]
Here is what you have to be doing: https://github.com/agneym/preact-cli-tailwind-example

Feel free to repoen the issue.
